# yamllint disable rule:truthy
# yamllint disable rule:indentation
# yamllint disable rule:line-length
name: build image

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
    tags:
    - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - id: docker_username
      uses: Entepotenz/change-string-case-action-min-dependencies@v1.1.0
      with:
        string: ${{github.repository_owner}}
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ${{ steps.docker_username.outputs.lowercase }}/alpine-unbound
          ghcr.io/${{ steps.docker_username.outputs.lowercase }}/alpine-unbound
        tags: |
          type=edge,branch=main
          type=schedule,pattern={{date 'YYYY[w]WW[d]]d'}}
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=sha
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        username: ${{ steps.docker_username.outputs.lowercase }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Login to GHCR
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
